pid /tmp/abrahamicbooks-nginx-test.pid;
error_log stderr notice;

events {}

http {
    access_log /tmp/abrahamicbooks-nginx-test-access.log;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    include "/home/abbas/Abrahamic Books/deploy/nginx/abrahamicbooks.org.conf";
}
